<a href="https://colab.research.google.com/github/trailblazer015/learn-python/blob/data-science-for-quant/pandas/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
delays_df = pd.read_csv('Lots_of_flight_data.csv')
delays_df.dropna(inplace=True)
delays_df.shape

(180525, 16)

In [3]:
#飞行距离和飞行时间
X=delays_df.loc[:,['DISTANCE','CRS_ELAPSED_TIME']]
X.head()

   DISTANCE  CRS_ELAPSED_TIME
0    1670.0               225
1    1670.0               225
2     580.0               105
3     580.0               105
4     580.0               100

In [4]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180525 entries, 0 to 182483
Data columns (total 2 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DISTANCE          180525 non-null  float64
 1   CRS_ELAPSED_TIME  180525 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 4.1 MB

In [5]:
#晚点时间
y=delays_df.loc[:,['ARR_DELAY']]
y.head()

   ARR_DELAY
0      -17.0
1      -25.0
2      -13.0
3      -12.0
4       -7.0

In [6]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180525 entries, 0 to 182483
Data columns (total 1 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ARR_DELAY  180525 non-null  float64
dtypes: float64(1)
memory usage: 2.8 MB

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42)

In [8]:
X_train.shape

(126367, 2)

In [9]:
X_test.shape

(54158, 2)

In [10]:
X_train.head()

        DISTANCE  CRS_ELAPSED_TIME
135016     337.0                88
6699       440.0                98
94554     1065.0               180
117331     474.0               123
1257       925.0               150

In [11]:
y_train.head()

        ARR_DELAY
135016      -20.0
6699        -18.0
94554        -7.0
117331       53.0
1257        -14.0

In [12]:
  from sklearn.linear_model import LinearRegression
  regressor=LinearRegression()
  regressor.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=regressor.predict(X_test)

In [14]:
#root mean square value
from sklearn.metrics import mean_squared_error
import numpy as np
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(rmse)

45.19019788552247