<a href="https://colab.research.google.com/github/trailblazer015/learn-python/blob/data-science-for-quant/pandas/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
delays_df = pd.read_csv('Lots_of_flight_data.csv')
delays_df.shape

(300000, 16)

In [10]:
#飞行距离和飞行时间
X=delays_df.loc[:,['DISTANCE','CRS_ELAPSED_TIME']]
X.head()

   DISTANCE  CRS_ELAPSED_TIME
0      1670               225
1      1670               225
2       580               105
3       580               105
4       580               100

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 2 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DISTANCE          300000 non-null  int64
 1   CRS_ELAPSED_TIME  300000 non-null  int64
dtypes: int64(2)
memory usage: 4.6 MB

In [5]:
#晚点时间
y=delays_df.loc[:,['ARR_DELAY']]
y.head()

   ARR_DELAY
0      -17.0
1      -25.0
2      -13.0
3      -12.0
4       -7.0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42)

In [13]:
X_train.shape

(210000, 2)

In [14]:
X_test.shape

(90000, 2)

In [15]:
X_train.head()

        DISTANCE  CRS_ELAPSED_TIME
186295       237                60
127847       411               111
274740       342                85
74908       1005               164
11630        484               100

In [16]:
y_train.head()

        ARR_DELAY
186295       -7.0
127847      -16.0
274740      -10.0
74908       -19.0
11630       -13.0