<a href="https://colab.research.google.com/github/trailblazer015/learn-python/blob/data-science-for-quant/pandas/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
delays_df = pd.read_csv('Lots_of_flight_data.csv')
delays_df.dropna(inplace=True)
delays_df.shape

(290930, 16)

In [4]:
#飞行距离和飞行时间
X=delays_df.loc[:,['DISTANCE','CRS_ELAPSED_TIME']]
X.head()

   DISTANCE  CRS_ELAPSED_TIME
0    1670.0             225.0
1    1670.0             225.0
2     580.0             105.0
3     580.0             105.0
4     580.0             100.0

In [5]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290930 entries, 0 to 295047
Data columns (total 2 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DISTANCE          290930 non-null  float64
 1   CRS_ELAPSED_TIME  290930 non-null  float64
dtypes: float64(2)
memory usage: 6.7 MB

In [6]:
#晚点时间
y=delays_df.loc[:,['ARR_DELAY']]
y.head()

   ARR_DELAY
0      -17.0
1      -25.0
2      -13.0
3      -12.0
4       -7.0

In [7]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290930 entries, 0 to 295047
Data columns (total 1 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ARR_DELAY  290930 non-null  float64
dtypes: float64(1)
memory usage: 4.4 MB

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42)

In [9]:
X_train.shape

(203651, 2)

In [10]:
X_test.shape

(87279, 2)

In [11]:
X_train.head()

        DISTANCE  CRS_ELAPSED_TIME
291460    2402.0             331.0
160350     350.0              81.0
169835    1096.0             199.0
5662      2611.0             342.0
93740      223.0              60.0

In [12]:
y_train.head()

        ARR_DELAY
291460       78.0
160350       -5.0
169835      -38.0
5662        -20.0
93740       -10.0

In [13]:
  from sklearn.linear_model import LinearRegression
  regressor=LinearRegression()
  regressor.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred=regressor.predict(X_test)

In [15]:
#root mean square value
from sklearn.metrics import mean_squared_error
import numpy as np
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(rmse)

46.61492991528989

In [16]:
type(y_pred)

numpy.ndarray

In [19]:
predicted_df=pd.DataFrame(y_pred)
type(predicted_df)

pandas.core.frame.DataFrame

In [21]:
predicted_df.head()

          0
0  5.939224
1  6.004687
2  6.036628
3  3.683718
4  5.559619