<a href="https://colab.research.google.com/github/trailblazer015/learn-python/blob/data-science-for-quant/pandas/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [18]:
delays_df = pd.read_csv('Lots_of_flight_data.csv')
delays_df.dropna(inplace=True)
delays_df.shape

(295832, 16)

In [19]:
#飞行距离和飞行时间
X=delays_df.loc[:,['DISTANCE','CRS_ELAPSED_TIME']]
X.head()

   DISTANCE  CRS_ELAPSED_TIME
0      1670               225
1      1670               225
2       580               105
3       580               105
4       580               100

In [20]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 295832 entries, 0 to 299999
Data columns (total 2 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DISTANCE          295832 non-null  int64
 1   CRS_ELAPSED_TIME  295832 non-null  int64
dtypes: int64(2)
memory usage: 6.8 MB

In [21]:
#晚点时间
y=delays_df.loc[:,['ARR_DELAY']]
y.head()

   ARR_DELAY
0      -17.0
1      -25.0
2      -13.0
3      -12.0
4       -7.0

In [23]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 295832 entries, 0 to 299999
Data columns (total 1 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ARR_DELAY  295832 non-null  float64
dtypes: float64(1)
memory usage: 4.5 MB

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42)

In [25]:
X_train.shape

(207082, 2)

In [26]:
X_test.shape

(88750, 2)

In [27]:
X_train.head()

        DISTANCE  CRS_ELAPSED_TIME
172560      1620               234
216512      1979               261
226502      1616               215
223830       944               151
179113       740               180

In [28]:
y_train.head()

        ARR_DELAY
172560      -11.0
216512        7.0
226502       -7.0
223830      -19.0
179113      -36.0

In [29]:
  from sklearn.linear_model import LinearRegression
  regressor=LinearRegression()
  regressor.fit(X_train,y_train)

LinearRegression()